Watchlist:
- AMD
- GOOGL
- INT
- MRVL
- NVDA
- NIO
- OUST

Followed news:
- Company related news
- General semiconductor news
- AI datacenters
- Humanoid robots
- Interest rates
- China EV

News pages checked always:
- Yahoo finance news
- Google finance news
- CnEVPost
- Reuters
- SEC-flings
- Company press releases
- FED
- ECB
- China authorities